base/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('finance.urls'))
]

finance/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.Index.as_view(), name='index'),
    url(r'^login/$', views.UserLogin.as_view(), name='login'),
    url(r'^registration/$',
        views.UserRegistration.as_view(),
        name='registration'),
    url(r'^logout/$', views.UserLogout.as_view(), name='logout'),
    url(r'^accounts/add/$', views.AccountsCreate.as_view(), name='new_account'),
    url(r'^account/update/(?P<pk>[0-9]+)/$',
        views.AccountUpdate.as_view(),
        name='update_account'),
    url(r'^account/delete/(?P<pk>[0-9]+)/$',
        views.AccountDelete.as_view(),
        name='delete_account'),
    url(r'^balance/add/$', views.BalanceCreate.as_view(), name='new_balance'),
    url(r'^balance/update/(?P<pk>[0-9]+)/$',
        views.BalanceUpdate.as_view(),
        name='update_balance'),
    url(r'^balance/delete/(?P<pk>[0-9]+)/$',
        views.BalanceDelete.as_view(),
        name='delete_balance')
]

finance/models.py
from django.db import models

OPERATIONS_TYPE = (
    ('I', 'Доход'),
    ('C', 'Расход')
)


class Categories(models.Model):
    name = models.CharField(max_length=250)
    operation_type = models.CharField(
        max_length=1, choices=OPERATIONS_TYPE, default='C')

    def __str__(self):
        return self.name


class Accounts(models.Model):
    STATUS = (
        ('I', 'Не используется'),
        ('A', 'Используется')
    )

    owner = models.ForeignKey('auth.User')
    name = models.CharField(max_length=250)
    score = models.FloatField()
    status = models.CharField(max_length=1, choices=STATUS, default='A')


class Balance(models.Model):
    date = models.DateField()
    operation = models.CharField(max_length=1, choices=OPERATIONS_TYPE)
    amount = models.FloatField()
    category = models.ForeignKey(Categories)
    user = models.ForeignKey('auth.User')
    account = models.ForeignKey(Accounts, null=True)

finance/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm
from .models import Balance, Accounts


class AccountsForm(ModelForm):
    class Meta:
        model = Accounts
        fields = ('name', 'score')

    def clean(self):
        cleaned_data = super(AccountsForm, self).clean()
        score = cleaned_data['score']
        if score <= 0:
            raise ValidationError('Сумма не може быть меньше или равна 0')
        return cleaned_data


class BalanceForm(ModelForm):
    class Meta:
        model = Balance
        fields = ('date', 'amount', 'category', 'account', 'operation')

    def clean(self):
        cleaned_data = super(BalanceForm, self).clean()
        account = cleaned_data['account']
        amount = cleaned_data['amount']
        if amount <= 0:
            raise ValidationError('Сумма не може быть меньше или равна 0')
        if cleaned_data['operation'] == 'C':
            if account.score < amount:
                raise ValidationError('Недостаточная сумма на счету')
            account.score -= amount
            account.save()
        else:
            account.score += amount
            account.save()
        return cleaned_data


class BalanceUpdateForm(ModelForm):
    class Meta:
        model = Balance
        fields = ('date', 'amount', 'category', 'account', 'operation')

    def clean(self):
        cleaned_data = super(BalanceUpdateForm, self).clean()
        account = cleaned_data['account']
        amount = cleaned_data['amount']
        if amount <= 0:
            raise ValidationError('Сумма не може быть меньше или равна 0')
        if cleaned_data['operation'] == 'C':
            if account.id is not self.instance.account.id:
                if account.score < amount:
                    raise ValidationError('Недостаточная сумма на счету')
                self.instance.account.score += self.instance.amount
                account.score -= amount
                self.instance.account.save()
                account.save()
            else:
                if amount > self.instance.amount:
                    if account.score - amount <= 0:
                        raise ValidationError('Недостаточная сумма на счету')
                    account.score -= (amount - self.instance.amount)
                    account.save()
                else:
                    print(self.instance.amount - amount)
                    account.score += (self.instance.amount - amount)
                    account.save()
        if cleaned_data['operation'] == 'I':
            if account.id is not self.instance.account.id:
                self.instance.account.score -= self.instance.amount
                account.score += amount
                self.instance.account.save()
                account.save()
            else:
                if amount > self.instance.amount:
                    account.score -= (self.instance.amount - amount)
                    account.save()
                else:
                    account.score += (amount - self.instance.amount)
                    account.save()
        return cleaned_data

finance/views.py
import datetime
from dateutil.relativedelta import relativedelta
from django.contrib.auth import login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.core.exceptions import ValidationError
from django.db.models import Sum
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.views.generic.base import RedirectView, TemplateView
from django.views.generic.edit import FormView, CreateView, UpdateView, DeleteView
from . import forms, models


class CheckAuth(object):
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated():
            return HttpResponseRedirect('/login/')
        return super(CheckAuth, self).dispatch(request, *args, **kwargs)


class CheckAccountOwner(CheckAuth):
    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        if not self.object.owner == request.user:
            return HttpResponseForbidden()
        return super(CheckAccountOwner, self).dispatch(
            request, *args, **kwargs)


class CheckBalanceUser(CheckAuth):
    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        if not self.object.user == request.user:
            return HttpResponseForbidden()
        return super(CheckBalanceUser, self).dispatch(request, *args, **kwargs)


class UserLogin(FormView):
    template_name = 'forms/login.jinja2'
    form_class = AuthenticationForm
    success_url = '/'

    def form_valid(self, form):
        if form.get_user():
            login(self.request, form.get_user())
            return super(UserLogin, self).form_valid(form)


class UserRegistration(FormView):
    template_name = 'forms/reg.jinja2'
    form_class = UserCreationForm
    success_url = '/login/'

    def form_valid(self, form):
        form.save()
        return super(UserRegistration, self).form_valid(form)


class UserLogout(RedirectView):
    url = '/'

    def get(self, request, *args, **kwargs):
        logout(request)
        return super(UserLogout, self).get(request, *args, **kwargs)


class Index(TemplateView):
    template_name = 'index.jinja2'

    def get_context_data(self, **kwargs):
        ctx = super(Index, self).get_context_data(**kwargs)
        date = datetime.date.today()
        accounts = models.Accounts.objects.filter(
            owner=self.request.user.id)
        if self.request.GET.get('prev', False):
            date = datetime.datetime.strptime(
                self.request.GET['date'], '%Y-%m-%d') - relativedelta(months=+1)
        if self.request.GET.get('next', False):
            date = datetime.datetime.strptime(
                self.request.GET['date'], '%Y-%m-%d') + relativedelta(months=+1)
        balance = models.Balance.objects.filter(
            user=self.request.user.id,
            date__month=date.month,
            date__year=date.year).order_by('date')
        ctx['accounts'] = accounts
        ctx['accounts_sum'] = accounts.filter(
            status='A').aggregate(Sum('score'))
        ctx['balance'] = balance
        ctx['total_cost'] = balance.filter(
            operation='C').aggregate(
            Sum('amount'))
        ctx['total_incom'] = balance.filter(
            operation='I').aggregate(Sum('amount'))
        ctx['today'] = date
        return ctx


class AccountsCreate(CheckAuth, CreateView):
    model = models.Accounts
    form_class = forms.AccountsForm
    template_name = 'forms/accounts_new_form.jinja2'
    success_url = '/'

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(AccountsCreate, self).form_valid(form)


class AccountUpdate(CheckAccountOwner, UpdateView):
    model = models.Accounts
    form_class = forms.AccountsForm
    template_name = 'forms/accounts_update_form.jinja2'
    success_url = '/'


class AccountDelete(CheckAuth, RedirectView):
    url = '/'

    def get(self, request, *args, **kwargs):
        account = models.Accounts.objects.get(pk=kwargs['pk'])
        if account.owner is not request.user:
            return HttpResponseForbidden()
        account.status = 'I'
        account.save()
        return super(AccountDelete, self).get(request, *args, **kwargs)


class BalanceCreate(CheckAuth, CreateView):
    model = models.Balance
    template_name = 'forms/balance_new_form.jinja2'
    success_url = '/'
    form_class = forms.BalanceForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(BalanceCreate, self).form_valid(form)

    def get_context_data(self, **kwargs):
        ctx = super(BalanceCreate, self).get_context_data(**kwargs)
        ctx['categories'] = models.Categories.objects.filter(
            operation_type=self.request.GET['type'])
        ctx['accounts'] = models.Accounts.objects.filter(
            owner=self.request.user.id,
            status='A')
        return ctx


class BalanceUpdate(CheckBalanceUser, UpdateView):
    model = models.Balance
    form_class = forms.BalanceUpdateForm
    success_url = '/'
    template_name = 'forms/balance_update_form.jinja2'

    def get_context_data(self, **kwargs):
        ctx = super(BalanceUpdate, self).get_context_data(**kwargs)
        ctx['accounts'] = models.Accounts.objects.filter(
            owner=self.request.user.id,
            status='A')
        ctx['categories'] = models.Categories.objects.filter(
            operation_type=self.request.GET['type'])
        return ctx


class BalanceDelete(CheckBalanceUser, DeleteView):
    model = models.Balance
    success_url = '/'

    def delete(self, request, *args, **kwargs):
        balance = self.get_object()
        if balance.operation == 'C':
            balance.account.score += balance.amount
        else:
            balance.account.score -= balance.amount
        balance.account.save()
        return super(BalanceDelete, self).delete(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

finance/templates/accounts_update_form.html
{% extends 'base.html' %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="inputName" class="sr-only">Название</label>
            <input id="inputName" name="name" type="text"  class="form-control" placeholder="Название" required="" value="{{ accounts.name }}">
        </div>
        <div class="form-group">
            <label for="inputScore" class="sr-only">Сумма</label>
            <input id="inputScore" name="score" type="number"  class="form-control" placeholder="Сумма" required="" value="{{ accounts.score | floatformat }}">
        </div>
        <a href="/" class="btn btn-secondary">Закрыть</a>
        <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>
{% endblock %}

finance/templates/balance_new_form.html
{% extends 'base.html' %}

{% block content %}
    <form id="newOperationForm" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="inputDate">Дата</label>
            <input id="inputDate" name="date" type="date"  class="form-control" placeholder="Дата" required="">
        </div>
        <div class="form-group">
            <label for="selectAccount">Счет</label>
            <select class="form-control" id="selectAccount" name="account">
                {% for acc in accounts %}
                    <option value="{{ acc.id }}">{{ acc.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <label for="selectCategory">Категория</label>
            <select class="form-control" id="selectCategory" name="category">
                {% for category in categories %}
                    <option value="{{ category.id }}">{{ category.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <label for="inputAmount">Сумма</label>
            <input id="inputAmount" name="amount" type="number"  class="form-control" placeholder="Сумма" required="">
        </div>
        <input type="hidden" name="operation" value="C">
        <a href="/" class="btn btn-secondary">Закрыть</a>
        <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>

{% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}
{% endblock %}

finance/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="ru">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- CSS-->
    <link rel="stylesheet" href={% static 'css/style.css' %} />
  </head>
  <body>
    <nav class="navbar navbar-inverse bg-inverse">
        <div class="container">
            <a class="navbar-brand" href="/">Finance App</a>
            {% if user.is_authenticated %}
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <p class="navbar-text">{{ request.user.username | upper }}</p>
                </li>
                <li><a href="/logout/">Выйти</a></li>
            </ul>
            {% endif %}
        </div>
    </nav>

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>

    <!-- jQuery first, then Bootstrap JS. -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!--<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>-->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="{% static 'js/script.js' %}"></script>
    </body>
</html>

finance/templates/base.jinja2
<!DOCTYPE html>
<html lang="ru">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Bootstrap datepicker css -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/css/bootstrap-datepicker.min.css">

    <!-- CSS-->
    <link rel="stylesheet" href="{{ static('css/style.css') }}" />
  </head>
  <body>
    <nav class="navbar navbar-inverse bg-inverse">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Finance App</a>
          </div>

            {% if request.user.is_authenticated() %}
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav navbar-right">
                  <li>
                      <p class="navbar-text">{{ request.user.username|upper }}</p>
                  </li>
                  <li><a href="/logout/">Выйти</a></li>
              </ul>
              {% endif %}
            </div>
        </div>
    </nav>

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>

    <!-- jQuery first, then Bootstrap JS. -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/js/bootstrap-datepicker.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/locales/bootstrap-datepicker.ru.min.js"></script>
    <script src="{{ static('js/script.js') }}""></script>
    </body>
</html>

finance/templates/form_errors.jinja2
{% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors() %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}

finance/templates/index.jinja2
{% extends 'base.jinja2' %}

{% block content %}
    {% if request.user.is_authenticated() %}
        <div class="row">
          <div class="col-md-12">
            <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
              <div class="panel panel-default">
                <div class="panel-heading" role="tab" id="headingOne">
                  <h4 class="panel-title">
                    <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                      Счета
                    </a>
                  </h4>
                </div>
                <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                  {% if accounts %}
                      <table class="table table-sm">
                          <thead class="thead-inverse">
                              <tr>
                                  <th class="col-md-6">Имя</th>
                                  <th class="col-md-4">Сумма</th>
                                  <th class="col-md-2"></th>
                              </tr>
                          </thead>
                          {% for acc in accounts %}
                              {% if acc.status == 'A' %}
                              <tbody>
                                  <tr>
                                      <td>{{ acc.name}}</td>
                                      <td>{{ acc.score}}</td>
                                      <td>
                                          <div class="btn-group" role="group">
                                              <a href="/account/update/{{ acc.id }}" class="btn btn-sm btn-outline-info">
                                                  <span class="glyphicon glyphicon glyphicon-pencil" aria-hidden="true"></span>
                                              </a>
                                              <button
                                                      class="btn btn-sm btn-outline-danger"
                                                      data-toggle="modal"
                                                      data-target="#deleteAccount"
                                                      data-account="{{acc.name}} {{acc.id}}"
                                               ><span class="glyphicon glyphicon glyphicon glyphicon-remove" aria-hidden="true"></span>
                                               </button>
                                          </div>
                                      </td>
                                  </tr>
                              </tbody>
                              {% endif %}
                          {% endfor %}
                      </table>
                      <div class="panel-body">
                          <h4>Итого: {{ accounts_sum.score__sum }}</h4>
                      </div>
                  {% else %}
                      <div class="panel-body">
                          счетов нет
                      </div>
                  {% endif %}
                  <div class="panel-footer">
                      <a href="/accounts/add/" class="btn btn-primary">Добавить счет</a>
                  </div>
                </div>
              </div>

              <div class="panel panel-default">
                <div class="panel-heading" role="tab" id="headingTwo">
                  <h4 class="panel-title">
                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                      За месяц
                    </a>
                  </h4>
                </div>
                <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
                  <div class="panel-body">
                      <p>Всего пришло: {{ total_incom.amount__sum or 0 }}</p>
                      <p>Всего потрачено: {{ total_cost.amount__sum or 0 }}</p>
                  </div>
                  <div class="panel-footer ">
                      <a href="/balance/add/?type=I" class="btn btn-primary">Добавить доход</a>
                      <a href="/balance/add/?type=C" class="btn btn-primary">Добавить расход</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-12">
            <div class="panel panel-default">
              <div class="panel-heading text-center">
                <div class="btn-group" role="group" aria-label="...">
                  <a href="/?prev=True&date={{ today.strftime('%Y-%m-%d') }}" type="button" class="btn btn-default">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                  </a>
                  <a href="/" type="button" class="btn btn-default">{{ today.strftime('%B %Y') }}</a>
                  <a href="/?next=True&date={{ today.strftime('%Y-%m-%d') }}" type="button" class="btn btn-default">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                  </a>
                </div>
              </div>

              <table class="table table-bordered table-responsive">
                  <thead>
                      <tr>
                        <th>Дата</th>
                        <th>Счет</th>
                        <th>Категория</th>
                        <th>Сумма</th>
                        <th>Операция</th>
                        <th></th>
                      </tr>
                  </thead>
                  <tbody>
                    {% for item in balance %}
                      <tr class="{{ 'success' if item.operation=='I' else 'danger' }}">
                        <td>{{ item.date.strftime('%d.%m.%Y') }}</td>
                        <td>{{ item.account.name }}</td>
                        <td>{{ item.category }}</td>
                        <td>{{ item.amount }}</td>
                        <td>{{ item.get_operation_display() }}</td>
                        <td>
                          <a href="/balance/update/{{ item.id }}/?type={{ item.operation}}" class="btn btn-sm btn-outline-info">
                              <span class="glyphicon glyphicon glyphicon-pencil" aria-hidden="true"></span>
                          </a></td>
                      </tr>
                    {% endfor %}
                  </tbody>
              </table>
            </div>
          </div>
        </div>
    {% else %}
    <div class="row">
      <div class="col-md-12">
        <h1>Вы не авторизованы</h1>
        <h3>Если у вас уже есть учетная запись, то перейдите на страницу <a href="/login/">входа</a></h3>
        <h3>Если у вас еще нет учетной записи, то перейдите на страницу <a href="/registration/">регистрации</a></h3>
      </div>
    </div>
    {% endif %}

<!-- Delete account form -->
{% include 'forms/accounts_delete_form.jinja2' %}

{% endblock %}

finance/templates/login.html
{% extends 'base.html' %}

{% block content %}
    <form class="form-signin login" method="POST">
        {% csrf_token %}
        <h3 class="form-heading">Войдите</h3>
        <label for="inputName" class="sr-only">Имя пользователя</label>
        <input id="inputName" name="username" type="text"  class="form-control" placeholder="Имя пользователя" required="">
        <label for="inputPassword" class="sr-only">Пароль</label>
        <input id="inputPassword" name="password" type="password"  class="form-control last-input" placeholder="Пароль" required="">
        <button class="btn btn-lg btn-primary btn-block" type="submit">Отправить</button>
    </form>

    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}
{% endblock %}

finance/templates/reg.html
{% extends 'base.html' %}

{% block content %}
    <form class="form-signin" method="POST">
        {% csrf_token %}
        <h3>Регистрация</h3>
        <label for="inputName" class="sr-only">Имя пользователя</label>
        <input id="inputName" name="username" type="text"  class="form-control" placeholder="Имя пользователя" required="">
        <label for="inputPassword" class="sr-only">Пароль</label>
        <input id="inputPassword" name="password1" type="password"  class="form-control middle-input" placeholder="Пароль" required="">
        <label for="confirmPassword" class="sr-only">Пароль</label>
        <input id="confirmPassword" name="password2" type="password"  class="form-control last-input" placeholder="Повторите пароль" required="">
        <button class="btn btn-lg btn-primary btn-block" type="submit">Отправить</button>
    </form>

    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}
{% endblock %}